import type { OdooSaleOrder, OdooOrderLine } from "@/lib/odoo/types";

export interface MockTimelineEntry {
  date: string;
  title: string;
  description?: string;
}

export interface MockOrderData {
  order: OdooSaleOrder;
  lines: OdooOrderLine[];
  timeline: MockTimelineEntry[];
}

const MOCK_ORDERS: MockOrderData[] = [
  {
    order: {
      id: 1,
      name: "SO-2025-001",
      partner_id: [42, "Metalúrgica Cuyo S.R.L."],
      partner_invoice_id: [42, "Metalúrgica Cuyo S.R.L."],
      partner_shipping_id: [101, "Planta Principal — Luján de Cuyo"],
      date_order: "2025-01-28T10:30:00",
      state: "sale",
      order_line: [1, 2],
      amount_untaxed: 185000,
      amount_tax: 38850,
      amount_total: 223850,
      currency_id: [1, "ARS"],
      pricelist_id: [1, "Lista Industrial B2B"],
      payment_term_id: [1, "30 días fecha factura"],
      invoice_status: "invoiced",
      invoice_ids: [],
    },
    lines: [
      {
        id: 1,
        order_id: [1, "SO-2025-001"],
        product_id: [10, "Oxígeno Industrial — Tubo 10m³"],
        product_uom_qty: 5,
        qty_delivered: 5,
        price_unit: 25000,
        price_subtotal: 125000,
        price_total: 151250,
        tax_id: [1],
        name: "Oxígeno Industrial — Tubo 10m³",
        discount: 0,
      },
      {
        id: 2,
        order_id: [1, "SO-2025-001"],
        product_id: [20, "Regulador de Presión Oxígeno Harris 801"],
        product_uom_qty: 2,
        qty_delivered: 2,
        price_unit: 30000,
        price_subtotal: 60000,
        price_total: 72600,
        tax_id: [1],
        name: "Regulador de Presión Oxígeno Harris 801",
        discount: 0,
      },
    ],
    timeline: [
      {
        date: "2025-01-30T14:00:00",
        title: "Entrega completada",
        description: "Recibido en Planta Principal",
      },
      {
        date: "2025-01-29T08:15:00",
        title: "En camino",
        description: "Despacho desde depósito GASA",
      },
      {
        date: "2025-01-28T16:00:00",
        title: "Orden confirmada",
        description: "Pago aprobado — MercadoPago",
      },
      {
        date: "2025-01-28T10:30:00",
        title: "Orden creada",
      },
    ],
  },
  {
    order: {
      id: 2,
      name: "SO-2025-002",
      partner_id: [42, "Metalúrgica Cuyo S.R.L."],
      partner_invoice_id: [42, "Metalúrgica Cuyo S.R.L."],
      partner_shipping_id: [102, "Depósito — Godoy Cruz"],
      date_order: "2025-01-15T09:00:00",
      state: "sale",
      order_line: [3, 4, 5],
      amount_untaxed: 312000,
      amount_tax: 65520,
      amount_total: 377520,
      currency_id: [1, "ARS"],
      pricelist_id: [1, "Lista Industrial B2B"],
      payment_term_id: [1, "30 días fecha factura"],
      invoice_status: "invoiced",
      invoice_ids: [],
    },
    lines: [
      {
        id: 3,
        order_id: [2, "SO-2025-002"],
        product_id: [11, "CO₂ Alimenticio — Tubo 30kg"],
        product_uom_qty: 8,
        qty_delivered: 8,
        price_unit: 18000,
        price_subtotal: 144000,
        price_total: 174240,
        tax_id: [1],
        name: "CO₂ Alimenticio — Tubo 30kg",
        discount: 0,
      },
      {
        id: 4,
        order_id: [2, "SO-2025-002"],
        product_id: [30, "Soldadora MIG Esab 250A"],
        product_uom_qty: 1,
        qty_delivered: 1,
        price_unit: 120000,
        price_subtotal: 120000,
        price_total: 145200,
        tax_id: [1],
        name: "Soldadora MIG Esab 250A",
        discount: 0,
      },
      {
        id: 5,
        order_id: [2, "SO-2025-002"],
        product_id: [31, "Alambre MIG 0.8mm — Rollo 15kg"],
        product_uom_qty: 4,
        qty_delivered: 4,
        price_unit: 12000,
        price_subtotal: 48000,
        price_total: 58080,
        tax_id: [1],
        name: "Alambre MIG 0.8mm — Rollo 15kg",
        discount: 0,
      },
    ],
    timeline: [
      {
        date: "2025-01-18T11:00:00",
        title: "Completada",
        description: "Entrega confirmada por el cliente",
      },
      {
        date: "2025-01-17T07:30:00",
        title: "En camino",
      },
      {
        date: "2025-01-16T14:00:00",
        title: "Preparando despacho",
      },
      {
        date: "2025-01-15T09:00:00",
        title: "Orden creada",
      },
    ],
  },
  {
    order: {
      id: 3,
      name: "SO-2025-003",
      partner_id: [42, "Metalúrgica Cuyo S.R.L."],
      partner_invoice_id: [42, "Metalúrgica Cuyo S.R.L."],
      partner_shipping_id: [101, "Planta Principal — Luján de Cuyo"],
      date_order: "2025-02-05T14:20:00",
      state: "sale",
      order_line: [6],
      amount_untaxed: 75000,
      amount_tax: 15750,
      amount_total: 90750,
      currency_id: [1, "ARS"],
      pricelist_id: [1, "Lista Industrial B2B"],
      payment_term_id: [1, "30 días fecha factura"],
      invoice_status: "to invoice",
      invoice_ids: [],
    },
    lines: [
      {
        id: 6,
        order_id: [3, "SO-2025-003"],
        product_id: [12, "Argón 5.0 — Tubo 10m³"],
        product_uom_qty: 3,
        qty_delivered: 3,
        price_unit: 25000,
        price_subtotal: 75000,
        price_total: 90750,
        tax_id: [1],
        name: "Argón 5.0 — Tubo 10m³",
        discount: 0,
      },
    ],
    timeline: [
      {
        date: "2025-02-05T15:00:00",
        title: "Orden confirmada",
        description: "Pago aprobado — MercadoPago",
      },
      {
        date: "2025-02-05T14:20:00",
        title: "Orden creada",
      },
    ],
  },
  {
    order: {
      id: 4,
      name: "SO-2025-004",
      partner_id: [42, "Metalúrgica Cuyo S.R.L."],
      partner_invoice_id: [42, "Metalúrgica Cuyo S.R.L."],
      partner_shipping_id: [101, "Planta Principal — Luján de Cuyo"],
      date_order: "2024-12-10T11:00:00",
      state: "sale",
      order_line: [7, 8],
      amount_untaxed: 96000,
      amount_tax: 20160,
      amount_total: 116160,
      currency_id: [1, "ARS"],
      pricelist_id: [1, "Lista Industrial B2B"],
      payment_term_id: [1, "30 días fecha factura"],
      invoice_status: "invoiced",
      invoice_ids: [],
    },
    lines: [
      {
        id: 7,
        order_id: [4, "SO-2025-004"],
        product_id: [13, "Nitrógeno Industrial — Tubo 10m³"],
        product_uom_qty: 2,
        qty_delivered: 2,
        price_unit: 22000,
        price_subtotal: 44000,
        price_total: 53240,
        tax_id: [1],
        name: "Nitrógeno Industrial — Tubo 10m³",
        discount: 0,
      },
      {
        id: 8,
        order_id: [4, "SO-2025-004"],
        product_id: [32, "Máscara Fotosensible Esab Warrior Tech"],
        product_uom_qty: 4,
        qty_delivered: 4,
        price_unit: 13000,
        price_subtotal: 52000,
        price_total: 62920,
        tax_id: [1],
        name: "Máscara Fotosensible Esab Warrior Tech",
        discount: 0,
      },
    ],
    timeline: [
      {
        date: "2024-12-13T10:00:00",
        title: "Completada",
      },
      {
        date: "2024-12-12T08:00:00",
        title: "En camino",
      },
      {
        date: "2024-12-10T11:00:00",
        title: "Orden creada",
      },
    ],
  },
  {
    order: {
      id: 5,
      name: "SO-2025-005",
      partner_id: [42, "Metalúrgica Cuyo S.R.L."],
      partner_invoice_id: [42, "Metalúrgica Cuyo S.R.L."],
      partner_shipping_id: [102, "Depósito — Godoy Cruz"],
      date_order: "2024-11-22T16:45:00",
      state: "sale",
      order_line: [9],
      amount_untaxed: 200000,
      amount_tax: 42000,
      amount_total: 242000,
      currency_id: [1, "ARS"],
      pricelist_id: [1, "Lista Industrial B2B"],
      payment_term_id: [1, "30 días fecha factura"],
      invoice_status: "invoiced",
      invoice_ids: [],
    },
    lines: [
      {
        id: 9,
        order_id: [5, "SO-2025-005"],
        product_id: [14, "Acetileno — Tubo 7kg"],
        product_uom_qty: 10,
        qty_delivered: 10,
        price_unit: 20000,
        price_subtotal: 200000,
        price_total: 242000,
        tax_id: [1],
        name: "Acetileno — Tubo 7kg",
        discount: 0,
      },
    ],
    timeline: [
      {
        date: "2024-11-25T09:00:00",
        title: "Completada",
      },
      {
        date: "2024-11-23T07:00:00",
        title: "En camino",
      },
      {
        date: "2024-11-22T16:45:00",
        title: "Orden creada",
      },
    ],
  },
  {
    order: {
      id: 6,
      name: "SO-2025-006",
      partner_id: [42, "Metalúrgica Cuyo S.R.L."],
      partner_invoice_id: [42, "Metalúrgica Cuyo S.R.L."],
      partner_shipping_id: [101, "Planta Principal — Luján de Cuyo"],
      date_order: "2024-10-05T08:30:00",
      state: "cancel",
      order_line: [10],
      amount_untaxed: 50000,
      amount_tax: 10500,
      amount_total: 60500,
      currency_id: [1, "ARS"],
      pricelist_id: [1, "Lista Industrial B2B"],
      invoice_status: "no",
      invoice_ids: [],
    },
    lines: [
      {
        id: 10,
        order_id: [6, "SO-2025-006"],
        product_id: [15, "Mezcla Argón/CO₂ 80/20 — Tubo 10m³"],
        product_uom_qty: 2,
        qty_delivered: 2,
        price_unit: 25000,
        price_subtotal: 50000,
        price_total: 60500,
        tax_id: [1],
        name: "Mezcla Argón/CO₂ 80/20 — Tubo 10m³",
        discount: 0,
      },
    ],
    timeline: [
      {
        date: "2024-10-06T10:00:00",
        title: "Cancelada",
        description: "Cancelada por el cliente",
      },
      {
        date: "2024-10-05T08:30:00",
        title: "Orden creada",
      },
    ],
  },
  {
    order: {
      id: 7,
      name: "SO-2025-007",
      partner_id: [42, "Metalúrgica Cuyo S.R.L."],
      partner_invoice_id: [42, "Metalúrgica Cuyo S.R.L."],
      partner_shipping_id: [101, "Planta Principal — Luján de Cuyo"],
      date_order: "2025-02-03T13:10:00",
      state: "draft",
      order_line: [11, 12],
      amount_untaxed: 154000,
      amount_tax: 32340,
      amount_total: 186340,
      currency_id: [1, "ARS"],
      pricelist_id: [1, "Lista Industrial B2B"],
      invoice_status: "no",
      invoice_ids: [],
    },
    lines: [
      {
        id: 11,
        order_id: [7, "SO-2025-007"],
        product_id: [10, "Oxígeno Industrial — Tubo 10m³"],
        product_uom_qty: 4,
        qty_delivered: 4,
        price_unit: 25000,
        price_subtotal: 100000,
        price_total: 121000,
        tax_id: [1],
        name: "Oxígeno Industrial — Tubo 10m³",
        discount: 0,
      },
      {
        id: 12,
        order_id: [7, "SO-2025-007"],
        product_id: [33, "Guantes de Soldador Largos — Par"],
        product_uom_qty: 12,
        qty_delivered: 12,
        price_unit: 4500,
        price_subtotal: 54000,
        price_total: 65340,
        tax_id: [1],
        name: "Guantes de Soldador Largos — Par",
        discount: 0,
      },
    ],
    timeline: [
      {
        date: "2025-02-03T13:10:00",
        title: "Presupuesto creado",
      },
    ],
  },
];

export function getMockOrders(partnerId: number): MockOrderData[] {
  return MOCK_ORDERS.filter((o) => o.order.partner_id[0] === partnerId);
}

export function getMockOrder(orderId: number): MockOrderData | undefined {
  return MOCK_ORDERS.find((o) => o.order.id === orderId);
}
